### ISSUE TITLE
Resources Jekyll collection

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#104]
Based on this sheet: https://docs.google.com/spreadsheets/d/1xJpgr8JBG9TgZF2mHB8Vjnhu453No4dHoNjFIhb0FQw/edit#gid=0

See `Column C - Hosted on (calitp.org)` and filter to `Resources Page` for the list to use for this collection.

- `category`: values in `Column B`
- `tags`: values in `Column D`
- `title`: values in `Column F`
- `asset`: values in `Column G`
- `date`

## Tasks

- [x] define collection in Jekyll
- [x] define collection items based on existing Resources (see above)
- [x] define template to render list of Resources
