### ISSUE TITLE
Press Release Jekyll collection

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#106]
Based on this sheet: https://docs.google.com/spreadsheets/d/1xJpgr8JBG9TgZF2mHB8Vjnhu453No4dHoNjFIhb0FQw/edit#gid=0

See `Column C - Hosted on (calitp.org)` and filter to `Press Page` for the list to use for this collection.

## Tasks

- [x] define collection in Jekyll
- [x] define collection items based on existing Press Releases (see above)
- [x] define template to render list of Press Releases
- [x] define template to render individual Press Release
