### ISSUE TITLE
Update spacing in Initiatives

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#177]
From https://github.com/cal-itp/calitp.org/issues/157#issuecomment-1585073506

- [x] center content within the rhombus in Desktop/Tablet #193
- [x] adjust vertical spacing for all sections to 40px Desktop, 28px Mobile #194
- [ ] ensure 8px of padding between all Recent News/Resources links #198
