### ISSUE TITLE
Page metadata should be specific to the page

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#254]
Right now we [hardcode the `<meta>` tags](https://github.com/cal-itp/calitp.org/blob/main/src/_includes/meta.html) to the `site` variables, e.g. `site.title` and `site.description`.

This means when links unfurl in e.g. social media or Slack, we always get the default site details instead of the specifics for the link itself (e.g. a Press Release).

All metadata should be specific to the page in question, and only fallback to the `site` configuration when page-level config is unavailable.

## Todo

- [ ] Confirm default page title (browser tabs, link unfurls) for homepage: `Cal-ITP: California Integrated Travel Project`
- [ ] Confirm default page description (link unfurls) for homepage: `A state government initiative, Cal-ITP is making riding by rail and bus simpler and more cost-effective—for California transit providers and riders.`
- [ ] Figure out page title (browser tabs, link unfurls) format for `/press`, `/press/<release>`, and `/resources`
- [ ] Figure out description (link unfurls) for `/press` and `/resources`
- [ ] Confirm using `press.intro` for `/press/<release>` description (link unfurls)

**Comment by thekaveman** [comment]
Thanks @mrose914 super helpful examples! Will have a PR for your review today.
