### ISSUE TITLE
[TRACKING] Add new partners info to calitp.org

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#318]
As part of our roadmap conversations in Jan 2024, we received a request to incorporate more information about our partners (CARB and CDT) into the calitp.org content. 

- [x] #319
- [x] #320
- [x] #321
- [x] Review Design at Websites Monthly on 7/3 
- [x] Get approval from GG on 7/3 
- [x] Get approvals from CARB 
- [x] Get approvals from CDT
- [ ] Get approvals from CalSTA 
- [x] Design Review mtg 
- [x] Decompose tickets for implementation 
- [x] Implement new content and push to staging 
- [ ] Final sign off

**Comment by machikoyasuda** [comment]
Completed on 9/9
