### ISSUE TITLE
[TRACKING] Add Customer Stories to calitp.org

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#345]
- [x] Develop content including agencies + homepage content 
- [x] Review Design at Websites Monthly on 7/3 
- [x] Get approval from GG on 7/3 
- [x] Get approval from Evan on Data Quality Stats
- [x] Get approval from Andy on Benefits Stats 
- [x] Get approval from Payments team on Payments Stats 
- [ ] Get approvals from CalSTA
- [x] VCTC Approval 
- [ ] Glenn County Approval 
- [ ] MST Approval
- [x] Design Review mtg 
- [x] Decompose tickets for implementation 
- [x] Implement new content and push to staging 
- [ ] Final sign off

**Comment by machikoyasuda** [comment]
Completed on 9/9
