### ISSUE TITLE
[TRACKING] Update CTAs for newsletter sign ups on calitp.org

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#346]
![Screenshot 2024-07-05 at 2 20 04 PM](https://github.com/cal-itp/calitp.org/assets/3137409/e748cd23-60ba-4546-8570-56f89d9d3d65)

We should refresh the CTA to stay connected to reflect the latest in newsletter options

- [ ] Confirm existing language around the Caltrans Mobility Newsletter newsletter
- [ ] Determine CTA for Benefits newsletter (cc @indexing) 
- [ ] Determine CTA for CS newsletter (@AnthonyRollins)

We may be able to link to sign up forms for add'l newsletter, add copy to the body content of the page to direct folks to more information / existing newsletters or something else. We can do this following the release of the calitp.org refresh / once ready.

cc @ohmegasquared

**Comment by indexing** [comment]
@mrose914 The CTA to subscribe to the Benefits Monthly Update is now live: https://share.hsforms.com/1uC9WaFRTQJOgZXEgplZrRQ3aanu

**Comment by AnthonyRollins** [comment]
@mrose914 We won't need to publicize the CS newsletter on the website. Our biggest website CTA would be to reach out for any questions using the `hello@`.

**Comment by indexing** [comment]
@mrose914 Agreed. Option 2 works for me. We can begin within the initiative and Customer Stories pages only and expand later as we see fit. The current name of the monthly newsletter for Benefits is the `Benefits Monthly Update`, so I'd propose we refer to it as such wherever we provide promote sign-ups. 

Thanks for the thoughtful summary of trade-offs!
