### ISSUE TITLE
Configure repo with devcontainer

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#37]
## Background

This repo has a [`compose.yml`](https://github.com/cal-itp/website/blob/main/compose.yml) file that makes development and running locally fairly straightforward.

But we are trying to standardize on devcontainers with pre-commit and other tooling to streamline the dev experience and ease future onboarding.

## Tasks

* [ ] `mkdir .devcontainer`
* [ ] `mv compose.yml .devcontainer/compose.yml`
* [ ] `touch .devcontainer/devcontainer.json` - see the [Benefits `devcontainer.json`](https://github.com/cal-itp/benefits/blob/dev/.devcontainer/devcontainer.json) as an example
* [ ] Rework Docker to install both jekyll (ruby) and pre-commit (python)
* [ ] `touch .pre-commit-config.yaml` - see the [Benefits `.pre-commit-config.yaml`](https://github.com/cal-itp/benefits/blob/dev/.pre-commit-config.yaml) as an example
* [ ] Configure a `postAttach.sh` script to setup pre-commit in the devcontainer
* [ ] Update README with new steps to get started
