### ISSUE TITLE
Audit of microsite + calitp.org roadmap

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#71]
TODOs:

- [x] Audit microsite https://bit.ly/m/cal-itp
- [x] Audit calitp.org 
- [x] Propose calitp.org roadmap 
- [x] Review microsite and roadmap during workshop session on 1/19 

Goals: 

- Align on key audiences for all calitp web properties (who are they, how do they learn about calitp, etc) 
- Determine JTBD (jobs to be done) for each audience 
- Assess how the current websites are doing re: JTBD 
- Prioritize improvements, additions, redesigns etc

**Comment by thekaveman** [comment]
Just a heads up @mrose914, I moved this issue into the `calitp.org` repo (from MobiMart)
